# Generated by Django 5.1.2 on 2024-12-02 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_feedback_delete_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_oredered',
            new_name='date_ordered',
        ),
    ]
